version: "3.8"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver_express
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Spike@888"
      ACCEPT_EULA: "Y"
    restart: always
    networks:
      - my_network
    volumes:
      - sqlserver_data:/var/opt/mssql

networks:
  my_network:
    driver: bridge

volumes:
  sqlserver_data:
    driver: local
